In [1]:
import numpy as np

# 1. DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray (n-dimensions array)
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [18]:
a2 = np.array([[1., 2., 3.3],
              [4., 5., 6.5]])

a3 = np.array([[[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [5]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [12]:
a2.shape

(2, 3)

In [13]:
a3.shape

(2, 3, 3)

In [16]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [19]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [20]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [21]:
type(a1), type(a2), type(a3) 

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [23]:
# Create a DataFrame from a Numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# 2. Create Numpy Array

In [25]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [26]:
sample_array.dtype

dtype('int32')

In [27]:
ones = np.ones((2, 3))

In [28]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
ones.dtype

dtype('float64')

In [30]:
type(ones)

numpy.ndarray

In [31]:
zeros = np.zeros((2, 3))

In [32]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
range_array = np.arange(0, 10, 2)

In [34]:
range_array

array([0, 2, 4, 6, 8])

In [36]:
random_array = np.random.randint(0, 10, size = (3, 5))

In [37]:
random_array

array([[9, 7, 1, 6, 2],
       [4, 5, 7, 4, 3],
       [2, 7, 1, 9, 6]])

In [38]:
random_array.size

15

In [39]:
random_array.shape

(3, 5)

In [42]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.20662858, 0.65644759, 0.38451383],
       [0.24011457, 0.11218497, 0.99449536],
       [0.97616487, 0.5860281 , 0.91730328],
       [0.36598391, 0.76963069, 0.62382312],
       [0.22399317, 0.3839859 , 0.20859016]])

In [43]:
random_array_2.shape

(5, 3)

In [46]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.14078744, 0.97806226, 0.12895426],
       [0.10510974, 0.20106541, 0.9671741 ],
       [0.49277642, 0.6834481 , 0.16152361],
       [0.780664  , 0.78319669, 0.36002496],
       [0.28561171, 0.28045899, 0.72285295]])

# 3. Numpy Random Seed

In [58]:
# Psudo-random numbers
np.random.seed(seed = 0)
random_array_4 = np.random.randint(19, size = (5, 3))
random_array_4

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 18,  4],
       [ 6, 12,  1],
       [ 6,  7, 14]])

In [64]:
np.random.seed(7)
random_array_5 = np.random.randint(19, size = (5, 3))
random_array_5

array([[15,  4,  3],
       [ 7, 14,  8],
       [14, 10,  8],
       [ 7,  6,  4],
       [16,  7, 12]])